import Footer from "@/components/mainComponents/layout/Footer";
import Navbar from "@/components/mainComponents/layout/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <AuthProvider>
      <Navbar />
      {children}
      <Footer />
      <Toaster position="top-right" />
    </AuthProvider>
  );
}
